/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu_Administracao;

import conexao_Mysql.administracaoInsertBD;
import conexao_Mysql.connection_BD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import conexao_Mysql.administracaoGetSet;

/**
 *
 * @author
 */
public class cadastro_Admin extends javax.swing.JFrame {

    /**
     * Creates new form gerenciamento_Admin
     */
    public cadastro_Admin() {
        initComponents();
        listarAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_Fundo = new javax.swing.JPanel();
        painel_Azul = new javax.swing.JPanel();
        icon_Cracha = new javax.swing.JLabel();
        label_Data = new javax.swing.JLabel();
        nome_Admin = new javax.swing.JTextField();
        label_Senha = new javax.swing.JLabel();
        label_CadastroAdmin1 = new javax.swing.JLabel();
        label_Nome1 = new javax.swing.JLabel();
        data_Nasc = new javax.swing.JFormattedTextField();
        button_LimparDados = new javax.swing.JButton();
        senha_Admin = new javax.swing.JTextField();
        button_CriarUser = new javax.swing.JButton();
        painel_Branco = new javax.swing.JPanel();
        icon_Edit = new javax.swing.JLabel();
        label_EdicaoAdmin = new javax.swing.JLabel();
        campo_Pesquisa = new javax.swing.JTextField();
        button_Pesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Administracao = new javax.swing.JTable();
        button_Editar1 = new javax.swing.JButton();
        Close = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_Fundo.setLayout(null);

        painel_Azul.setBackground(new java.awt.Color(0, 0, 51));
        painel_Azul.setLayout(null);

        icon_Cracha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_Cracha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu_Administracao/CRACHA.png"))); // NOI18N
        painel_Azul.add(icon_Cracha);
        icon_Cracha.setBounds(160, 50, 50, 40);

        label_Data.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label_Data.setForeground(new java.awt.Color(255, 255, 255));
        label_Data.setText("Data de Nascimento:");
        painel_Azul.add(label_Data);
        label_Data.setBounds(30, 210, 140, 16);

        nome_Admin.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        nome_Admin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_AdminActionPerformed(evt);
            }
        });
        painel_Azul.add(nome_Admin);
        nome_Admin.setBounds(30, 170, 270, 20);

        label_Senha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label_Senha.setForeground(new java.awt.Color(255, 255, 255));
        label_Senha.setText("Senha:");
        painel_Azul.add(label_Senha);
        label_Senha.setBounds(30, 270, 70, 16);

        label_CadastroAdmin1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label_CadastroAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        label_CadastroAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_CadastroAdmin1.setText("Cadastro de Administradores");
        label_CadastroAdmin1.setToolTipText("");
        label_CadastroAdmin1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_Azul.add(label_CadastroAdmin1);
        label_CadastroAdmin1.setBounds(10, 10, 320, 50);

        label_Nome1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label_Nome1.setForeground(new java.awt.Color(255, 255, 255));
        label_Nome1.setText("Nome Completo:");
        painel_Azul.add(label_Nome1);
        label_Nome1.setBounds(30, 150, 100, 16);

        try {
            data_Nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data_Nasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_Nasc.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        painel_Azul.add(data_Nasc);
        data_Nasc.setBounds(30, 230, 270, 20);

        button_LimparDados.setText("LIMPAR CAMPOS");
        button_LimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LimparDadosActionPerformed(evt);
            }
        });
        painel_Azul.add(button_LimparDados);
        button_LimparDados.setBounds(30, 330, 130, 23);

        senha_Admin.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        senha_Admin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senha_Admin.setToolTipText("");
        painel_Azul.add(senha_Admin);
        senha_Admin.setBounds(30, 290, 270, 20);

        button_CriarUser.setText("CADASTRAR");
        button_CriarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CriarUserActionPerformed(evt);
            }
        });
        painel_Azul.add(button_CriarUser);
        button_CriarUser.setBounds(200, 330, 100, 23);

        painel_Fundo.add(painel_Azul);
        painel_Azul.setBounds(0, 0, 340, 510);

        painel_Branco.setBackground(new java.awt.Color(51, 153, 255));
        painel_Branco.setLayout(null);

        icon_Edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEDRO\\Documents\\NetBeansProjects\\crud\\src\\ICONS\\EDITICON.png")); // NOI18N
        painel_Branco.add(icon_Edit);
        icon_Edit.setBounds(450, 80, 86, 50);

        label_EdicaoAdmin.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label_EdicaoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        label_EdicaoAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_EdicaoAdmin.setText("Edição de Usuários Administradores");
        label_EdicaoAdmin.setToolTipText("");
        label_EdicaoAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painel_Branco.add(label_EdicaoAdmin);
        label_EdicaoAdmin.setBounds(70, 60, 400, 50);

        campo_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_PesquisaActionPerformed(evt);
            }
        });
        painel_Branco.add(campo_Pesquisa);
        campo_Pesquisa.setBounds(230, 140, 240, 30);

        button_Pesquisar.setText("Pesquisar");
        button_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PesquisarActionPerformed(evt);
            }
        });
        painel_Branco.add(button_Pesquisar);
        button_Pesquisar.setBounds(70, 140, 150, 30);

        jPanel1.setLayout(null);

        table_Administracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Data de Nascimento", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Administracao);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 400, 230);

        painel_Branco.add(jPanel1);
        jPanel1.setBounds(70, 180, 400, 230);

        button_Editar1.setText("Editar usuario");
        button_Editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Editar1ActionPerformed(evt);
            }
        });
        painel_Branco.add(button_Editar1);
        button_Editar1.setBounds(350, 420, 120, 23);

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEDRO\\Documents\\NetBeansProjects\\crud\\src\\ICONS\\CLOSE.png")); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        painel_Branco.add(Close);
        Close.setBounds(510, 10, 50, 40);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEDRO\\Documents\\NetBeansProjects\\crud\\src\\ICONS\\BACK-ARROW.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        painel_Branco.add(back);
        back.setBounds(470, 10, 32, 40);

        painel_Fundo.add(painel_Branco);
        painel_Branco.setBounds(340, 0, 570, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(916, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        
        //Object[] options = { "Confirmar", "Cancelar" };
        //JOptionPane.showOptionDialog(null, "<html><i>Você ira perder a autenticação se confirmar!</i>"+"<br>"+"<i> Deseja realmente sair?</i></html>", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);    
        
        
      
            tela_Decisao_Admin_Aluno acesso = new tela_Decisao_Admin_Aluno(); 
            acesso.setVisible(true);

            dispose(); //Fecha a tela de login
        
        
        
      
        
 
    }//GEN-LAST:event_backMouseClicked

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        
        //FUNÇÃO DE CONFIRMAÇÃO
        String message = "<html><i>Deseja fechar o programa?</i></html>";
        String title = "Confirmação";
        //Exibe caixa de dialogo (veja figura) solicitando confirmação ou não. 
        //Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION)
          {
            dispose(); //Fecha a tela de login
          }
    }//GEN-LAST:event_CloseMouseClicked

    private void campo_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_PesquisaActionPerformed

    private void button_Editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Editar1ActionPerformed
        // TODO add your handling code here:
        /*
        alterar_Admin acesso = new alterar_Admin(); 
        acesso.setVisible(true);
        */
        editar_Admin acesso = new editar_Admin(); 
        acesso.setVisible(true);

            dispose(); //Fecha a tela de login
        
        
    }//GEN-LAST:event_button_Editar1ActionPerformed

    private void nome_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_AdminActionPerformed

    private void button_LimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LimparDadosActionPerformed
        // TODO add your handling code here:
        LimparCampos();
       
    }//GEN-LAST:event_button_LimparDadosActionPerformed

    private void button_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PesquisarActionPerformed
        // TODO add your handling code here:
        listarAdmin();
    }//GEN-LAST:event_button_PesquisarActionPerformed

    private void button_CriarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CriarUserActionPerformed
        // TODO add your handling code here:
        cadastrar_Admin();
        listarAdmin();
        LimparCampos();
    }//GEN-LAST:event_button_CriarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel back;
    private javax.swing.JButton button_CriarUser;
    private javax.swing.JButton button_Editar1;
    private javax.swing.JButton button_LimparDados;
    private javax.swing.JButton button_Pesquisar;
    private javax.swing.JTextField campo_Pesquisa;
    private javax.swing.JFormattedTextField data_Nasc;
    private javax.swing.JLabel icon_Cracha;
    private javax.swing.JLabel icon_Edit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_CadastroAdmin1;
    private javax.swing.JLabel label_Data;
    private javax.swing.JLabel label_EdicaoAdmin;
    private javax.swing.JLabel label_Nome1;
    private javax.swing.JLabel label_Senha;
    private javax.swing.JTextField nome_Admin;
    private javax.swing.JPanel painel_Azul;
    private javax.swing.JPanel painel_Branco;
    private javax.swing.JPanel painel_Fundo;
    private javax.swing.JTextField senha_Admin;
    private javax.swing.JTable table_Administracao;
    // End of variables declaration//GEN-END:variables

    //LISTAGEM DOS USUARIOS ADMINISTRADORES JA CRIADOS
    private void listarAdmin(){
        try{
            administracaoInsertBD objAdmin = new administracaoInsertBD();
            
            DefaultTableModel model = (DefaultTableModel) table_Administracao.getModel();
            model.setNumRows(0);
            
            ArrayList<administracaoGetSet> lista = objAdmin.pesquisarAdmin();
            
            
            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_Admin(),
                    lista.get(num).getNome_Admin(),
                    lista.get(num).getData_Admin(),
                    lista.get(num).getSenha_Admin()                       
                });
            }
            
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "cadastro_Admin - Método listarAdmin():" + erro);
        }
    }
    
    
    
    
    //CADASTRA UM NOVO USUARIO
    private void cadastrar_Admin(){
    // TODO add your handling code here:
         
        String nome = nome_Admin.getText(); //PEGA O NOME
        String data = data_Nasc.getText();
        String pwd = senha_Admin.getText(); //PEGA A SENHA
 
        if((nome_Admin.getText().isEmpty()) || (data_Nasc.getText().isEmpty()) || (senha_Admin.getText().isEmpty())){
            
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            
        }else{
        
        administracaoGetSet objAdministracao = new administracaoGetSet();
        objAdministracao.setNome_Admin(nome);
        objAdministracao.setData_Admin(data);
        objAdministracao.setSenha_Admin(pwd);
        
        administracaoInsertBD objAdministracaoBD = new administracaoInsertBD();
        objAdministracaoBD.cadastrarAdmin(objAdministracao);
        
        //JOptionPane.showMessageDialog(null, "Administrador cadastrado com sucesso!");
        
      }    
    }
 

    //FUNÇÃO RESPONSAVEL POR LIMPAR OS CAMPOS
    private void LimparCampos(){
        nome_Admin.setText("");
        data_Nasc.setText("");
        senha_Admin.setText("");
        
    }   
}
