/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu_Administracao;

import conexao_Mysql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import menu_Administracao.administracaoLoginConnectionBD;
import menu_Inicial.tela_Acesso;
/**
 *
 * @author PEDRO
 */
public class login_Administracao extends javax.swing.JFrame {

    /**
     * Creates new form login_Administracao
     */
    public login_Administracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_User = new javax.swing.JLabel();
        paineal_Branco = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        painel_Azul = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_Usuario = new javax.swing.JLabel();
        campo_Usuario = new javax.swing.JTextField();
        label_Senha = new javax.swing.JLabel();
        campo_Senha = new javax.swing.JPasswordField();
        button_Entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        icon_User.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEDRO\\Documents\\NetBeansProjects\\crud\\src\\ICONS\\USER.png")); // NOI18N
        getContentPane().add(icon_User);
        icon_User.setBounds(590, 40, 90, 90);

        paineal_Branco.setBackground(new java.awt.Color(255, 255, 255));
        paineal_Branco.setLayout(null);

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEDRO\\Documents\\NetBeansProjects\\crud\\src\\ICONS\\BACK-ARROW.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        paineal_Branco.add(back);
        back.setBounds(10, 10, 40, 32);

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\PEDRO\\Documents\\NetBeansProjects\\crud\\src\\ICONS\\CLOSE.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        paineal_Branco.add(close);
        close.setBounds(60, 10, 40, 30);

        getContentPane().add(paineal_Branco);
        paineal_Branco.setBounds(0, 0, 640, 510);

        painel_Azul.setBackground(new java.awt.Color(0, 0, 51));
        painel_Azul.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(14, 0, 200, 50);

        painel_Azul.add(jPanel3);
        jPanel3.setBounds(10, 60, 210, 50);

        label_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        label_Usuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        label_Usuario.setText("Usuário:");
        painel_Azul.add(label_Usuario);
        label_Usuario.setBounds(50, 180, 90, 16);

        campo_Usuario.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        painel_Azul.add(campo_Usuario);
        campo_Usuario.setBounds(50, 200, 150, 20);

        label_Senha.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        label_Senha.setForeground(new java.awt.Color(255, 255, 255));
        label_Senha.setText("Senha:");
        painel_Azul.add(label_Senha);
        label_Senha.setBounds(50, 240, 60, 16);

        campo_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_SenhaActionPerformed(evt);
            }
        });
        painel_Azul.add(campo_Senha);
        campo_Senha.setBounds(50, 260, 150, 20);

        button_Entrar.setBackground(new java.awt.Color(102, 102, 102));
        button_Entrar.setText("Entrar");
        button_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EntrarActionPerformed(evt);
            }
        });
        painel_Azul.add(button_Entrar);
        button_Entrar.setBounds(130, 300, 65, 23);

        getContentPane().add(painel_Azul);
        painel_Azul.setBounds(640, 0, 270, 510);

        setSize(new java.awt.Dimension(916, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campo_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_SenhaActionPerformed

    private void button_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EntrarActionPerformed
    
         Logar(); //Chama o método Logar nas ultimas linhas do codigo!
        
    }//GEN-LAST:event_button_EntrarActionPerformed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_backKeyPressed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        menu_Inicial.tela_Acesso acesso = new menu_Inicial.tela_Acesso(); 
        acesso.setVisible(true);
        
        dispose(); //Fecha a tela de login
        
    }//GEN-LAST:event_backMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
         //FUNÇÃO DE CONFIRMAÇÃO
        String message = "<html><i>Deseja fechar o programa?</i></html>";
        String title = "Confirmação";
        //Exibe caixa de dialogo (veja figura) solicitando confirmação ou não. 
        //Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
          if (reply == JOptionPane.YES_OPTION)
          {
            dispose(); //Fecha a tela de login
          }
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_Administracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton button_Entrar;
    private javax.swing.JPasswordField campo_Senha;
    private javax.swing.JTextField campo_Usuario;
    private javax.swing.JLabel close;
    private javax.swing.JLabel icon_User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_Senha;
    private javax.swing.JLabel label_Usuario;
    private javax.swing.JPanel paineal_Branco;
    private javax.swing.JPanel painel_Azul;
    // End of variables declaration//GEN-END:variables


//MÉTODO LOGAR
    private void Logar(){
    
    try {
            
            String nome_Admin, senha_Admin;

            nome_Admin = campo_Usuario.getText();
            senha_Admin = String.valueOf (campo_Senha.getPassword());

            administracaoGetSet objAdmin = new administracaoGetSet();
            objAdmin.setNome_Admin(nome_Admin);
            objAdmin.setSenha_Admin(senha_Admin);
            
            administracaoLoginConnectionBD objUser = new administracaoLoginConnectionBD();
            ResultSet rsUser = objUser.autenticacaoUser(objAdmin);
            
            if(rsUser.next()){
                //Chamar a proxima tela
                tela_Decisao_Admin_Aluno objTeste = new tela_Decisao_Admin_Aluno();
                objTeste.setVisible(true);
                
                dispose(); //Fecha a tela de login
            }else{
                //Enviar msg de erro, incorreto!
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválida");
            }
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "login_Administraao" + erro);
        }
    
    }

}
